### ISSUE TITLE
Using os_queryTimeCriticalJobs before sleeping and sleep wakeup

### ISSUE THREAD

**Issue by Praneethsvch** [JackGruber/Arduino-Pro-Mini-LoRa-Sensor-Node#2]
Hi JackGruber,

I am student and using your code I am additionally trying to implement os_queryTimeCriticalJobs before sleeping from one of your articles:  [ESP 32 DeepSleep and LoraWAN OTAA join](https://jackgruber.github.io/2020-04-13-ESP32-DeepSleep-and-LoraWAN-OTAA-join/) 

I believe an ideal scenario would look like:
<img width="1716" alt="events" src="https://user-images.githubusercontent.com/58634765/90433428-ce101500-e099-11ea-8b0e-7134135ab938.png">
with main loop being,

```
void loop(void) 
{
    os_runloop_once();
    int seconds = 300;
    if(!os_queryTimeCriticalJobs(ms2osticksRound( (seconds*1000) - 1000 )))
    {
        Serial.println("Can sleep");
        if(GOTO_DEEPSLEEP == true)
        {
           // sleep now
           MCU_sleep();
           // set GOTO_DEEPSLEEP false
           GOTO_DEEPSLEEP = false;
        }
    }
}
```

I would like to request for your valuable suggestion on the following:

1. Firstly I understand that the MCU is put to deep sleep between the transmits, i.e. a TX is scheduled for LORA_TX_INTERVAL and then goes to deep sleep. I see in the following PowerDownTXIntervall function, you have added sleep cycles + 1 which means MCU is going to sleep for a period little longer than LORA_TX_INTERVAL
```
void PowerDownTXIntervall()
{
    Serial.println(F("PowerDown..."));
    Serial.flush();        
    
    int sleep_cycles = LORA_TX_INTERVAL / 8;

    for (int i=0; i<=sleep_cycles+1; i++) 
    {
      PowerDownUpdateMicros();
    }

    Serial.println(F("PowerUp..."));
} 
```
But the next TX is scheduled after LORA_TX_INTERVAL and does this mean the MCU wakes up from sleep before the for loop is executed? and if yes, does it use interrupts?

2. Secondly, if it does wake up from sleep using interrupt, the `GOTO_DEEPSLEEP` would not be set back to false. Would there be a possible danger that the mcu sleeps indefinitely or blocking the next TX? 

Thank you for your valuable time!

**Comment by JackGruber** [comment]
Hi @Praneethsvch,

You mix the ESP and ATmega 328 topics ...

>Firstly I understand that the ...

Yes this is correct, but only 8 Seconds more. 
I had built this in as a compensation, so that I am below the Duty cycle limit at a 1 channel node. 

The ATmega 328 execute after a wake up the code at the same position and can store the variables during a DeepSleep. An ESP32 can't do this!

The addition of os_queryTimeCriticalJobs would look like this for this repro code which is for an ATmega 328:
```c++
void LoraWANDo(void)
{
    if(GO_DEEP_SLEEP == true AND !os_queryTimeCriticalJobs(ms2osticksRound( (seconds*1000) - 1000 )))
    {
      PowerDownTXIntervall();
      GO_DEEP_SLEEP = false;
    }
    else
    {
      os_runloop_once();
    }
}
```

> Secondly, if it does wake up from sleep using interrupt, the GOTO_DEEPSLEEP would not be set ...

The `GOTO_DEEPSLEEP` would be set to false in `void LoraWANDo(void)` on the ESP all vars are reinizialized after a deep sleep! 
Because the ESP32 reboots completely! 

In the next few days I will release a project for an ESP32, which has been running for months. 
Probably i will release also an update for the Arduino-Pro-Mini-LoRa-Sensor-Node. 

Regards
Alex

**Comment by Praneethsvch** [comment]
Thanks for your valuable reply and time!

**Comment by JackGruber** [comment]
@Praneethsvch https://github.com/JackGruber/esp32_ttn_environmental_sensor
